base:
  seed: 1111
  batch_size: 1
  num_workers: 8
  train_mode: regression # only support regression now
  key_eval: Non0_acc_2 # Has0_acc_2
  missing_rate_eval_test: 0   # used for evaluation and testing
  alpha: 0.9
  beta_max: 1.0
  gamma: 0.1
  curvature: 1.0
  hyp_warmup_epochs: 10
  hyp_margin: 0.1
  safety_margin: 0.00001
  ema_decay: 0.999


dataset:
  datasetName: mosi
  dataPath: /data/MSA Datasets/MOSI/Processed/unaligned_50.pkl


model:
  feature_extractor:
    bert_pretrained: '/data/model/bert-base-uncased'
    input_length: [50, 500, 375] # language, video, audio
    token_length: [8, 8, 8] # language, video, audio
    heads: 8
    input_dims: [768, 20, 5] # language, video, audio
    hidden_dims: [128, 128, 128] # language, video, audio
    depth: 2

  dmc:
    proxy_dominant_feature_generator:
      input_length: 24
      token_length: 8
      depth: 2
      heads: 8
      input_dim: 128
      hidden_dim: 128

    effectiveness_discriminator:
      input_dim: 128
      hidden_dim: 64
      out_dim: 2

    completeness_check:
      input_length: 8
      token_length: 1
      depth: 2
      heads: 8
      input_dim: 128
      hidden_dim: 128

  reconstructor:
    input_length: 8
    depth: 2
    heads: 8
    input_dim: 128
    hidden_dim: 128
      
  dmml:
    language_encoder:
      input_length: 8
      token_length: 8
      depth: 2
      heads: 8
      input_dim: 128
      hidden_dim: 128

    hyper_modality_learning:
      depth: 3
      heads: 8
      input_dim: 128
      hidden_dim: 128
    
    fuison_transformer:
      source_length: 8
      tgt_length: 8
      depth: 2
      heads: 8
      input_dim: 128
      hidden_dim: 128
    
    regression:
      input_dim: 128
      out_dim: 1

  hyper_params:
    hyper_depth: 3
    dim_head: 16
    hyp_dim: 128