base:
  seed: 1111
  batch_size: 32
  num_workers: 0
  kl: 0.5
  num_layers: 4
  attn_dropout: 0.5
  train_mode: regression # only support regression now
  key_eval: Mult_acc_2
  type: test #
  missing_rate_eval_test: 0   # used for evaluation and testing

dataset:
  datasetName: sims
  dataPath: ../data/MSA_Datasets/SIMS/Processed/unaligned_39.pkl
  

model:    
  feature_extractor:
    bert_pretrained: '../bert/bert-base-chinese'
    transformers: 'bert'  # transformers: bert
    input_length: [39, 55, 400] # language, video, audio
    token_length: [39, 39, 39] # language, video, audio
    heads: 8
    input_dims: [768, 709, 33] # language, video, audio
    hidden_dims: [128, 128, 128] # language, video, audio
    depth: 2

  vae:
    input_length: 8
    depth: 2
    heads: 8
    input_dim: 128
    hidden_dim: 128

  reconstructor:
    input_length: 8
    depth: 2
    heads: 8
    input_dim: 128
    hidden_dim: 128

  crossmodal_encoder:
    proxy_dim: 128
    hidden_dims: [128, 128, 128] # language, video, audio
    embed_dim: 128
    num_layers: 4
    attn_dropout: 0.5

  generate_proxy:
    input_dim: 128
    hidden_dim: 128
    out_dim: 128

  regression:
    attn_dropout: 0.5
    input_dim: 128
    hidden_dim: 128
    out_dim: 1
